-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 11:34:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema OpticsBottomBottle
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OpticsBottomBottle` ;

-- -----------------------------------------------------
-- Schema OpticsBottomBottle
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OpticsBottomBottle` DEFAULT CHARACTER SET utf8mb4 ;
USE `OpticsBottomBottle` ;

-- -----------------------------------------------------
-- Table `OpticsBottomBottle`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpticsBottomBottle`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `OpticsBottomBottle`.`Supplier` (
  `id_supplier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `addr_street` VARCHAR(75) NOT NULL,
  `addr_number` VARCHAR(12) NULL,
  `addr_floor` VARCHAR(12) NULL,
  `addr_door` VARCHAR(12) NULL,
  `city` VARCHAR(40) NOT NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `country` VARCHAR(40) NOT NULL,
  `num_phone` VARCHAR(15) NOT NULL,
  `num_fax` VARCHAR(15) NULL,
  `tax_code` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_supplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticsBottomBottle`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpticsBottomBottle`.`Customer` ;

CREATE TABLE IF NOT EXISTS `OpticsBottomBottle`.`Customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `addr_postal` VARCHAR(150) NOT NULL,
  `num_phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `registration_date` DATE NOT NULL,
  `id_referred` INT NULL,
  PRIMARY KEY (`id_customer`),
  INDEX `fk_Customer_Customer_idx` (`id_referred` ASC),
  CONSTRAINT `fk_Customer_Customer`
    FOREIGN KEY (`id_referred`)
    REFERENCES `OpticsBottomBottle`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticsBottomBottle`.`GlassesBrand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpticsBottomBottle`.`GlassesBrand` ;

CREATE TABLE IF NOT EXISTS `OpticsBottomBottle`.`GlassesBrand` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `id_suplier` INT NOT NULL,
  PRIMARY KEY (`id_brand`),
  INDEX `fk_GlassesBrand_Supliers_idx` (`id_suplier` ASC),
  CONSTRAINT `fk_GlassesBrand_Supliers`
    FOREIGN KEY (`id_suplier`)
    REFERENCES `OpticsBottomBottle`.`Supplier` (`id_supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticsBottomBottle`.`Glasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpticsBottomBottle`.`Glasses` ;

CREATE TABLE IF NOT EXISTS `OpticsBottomBottle`.`Glasses` (
  `id_glasses` INT NOT NULL AUTO_INCREMENT,
  `id_brand` INT NOT NULL,
  `prescription_right_lens` FLOAT NOT NULL,
  `prescription_left_lens` FLOAT NOT NULL,
  `frame_type` ENUM('metallic', 'plastic', 'floating') NOT NULL,
  `frame_color` VARCHAR(40) NOT NULL,
  `color_right_lens` VARCHAR(40) NOT NULL,
  `color_left_lens` VARCHAR(40) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id_glasses`),
  INDEX `fk_Glasses_GlassesBrand_idx` (`id_brand` ASC),
  CONSTRAINT `fk_Glasses_GlassesBrand`
    FOREIGN KEY (`id_brand`)
    REFERENCES `OpticsBottomBottle`.`GlassesBrand` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticsBottomBottle`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpticsBottomBottle`.`Employee` ;

CREATE TABLE IF NOT EXISTS `OpticsBottomBottle`.`Employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticsBottomBottle`.`SaleHeader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpticsBottomBottle`.`SaleHeader` ;

CREATE TABLE IF NOT EXISTS `OpticsBottomBottle`.`SaleHeader` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `id_customer` INT NOT NULL,
  `id_employee` INT NOT NULL,
  `sale_date` DATE NOT NULL,
  `sale_period` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `fk_SaleHeader_Customer_idx` (`id_customer` ASC),
  INDEX `fk_SaleHeader_Employee_idx` (`id_employee` ASC),
  CONSTRAINT `fk_SaleHeader_Customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `OpticsBottomBottle`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SaleHeader_Employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `OpticsBottomBottle`.`Employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OpticsBottomBottle`.`SaleDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OpticsBottomBottle`.`SaleDetails` ;

CREATE TABLE IF NOT EXISTS `OpticsBottomBottle`.`SaleDetails` (
  `id_detail` INT NOT NULL AUTO_INCREMENT,
  `id_sale` INT NOT NULL,
  `id_glasses` INT NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` FLOAT NOT NULL,
  PRIMARY KEY (`id_detail`),
  INDEX `fk_SaleDetail_Sale_idx` (`id_sale` ASC),
  INDEX `fk_SaleDetail_Glasses_idx` (`id_glasses` ASC),
  CONSTRAINT `fk_SaleDetail_Sale`
    FOREIGN KEY (`id_sale`)
    REFERENCES `OpticsBottomBottle`.`SaleHeader` (`id_sale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SaleDetail_Glasses`
    FOREIGN KEY (`id_glasses`)
    REFERENCES `OpticsBottomBottle`.`Glasses` (`id_glasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
