-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 11:37:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FoodDeliveryCompany
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FoodDeliveryCompany` ;

-- -----------------------------------------------------
-- Schema FoodDeliveryCompany
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FoodDeliveryCompany` DEFAULT CHARACTER SET utf8mb4 ;
USE `FoodDeliveryCompany` ;

-- -----------------------------------------------------
-- Table `FoodDeliveryCompany`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDeliveryCompany`.`Customer` ;

CREATE TABLE IF NOT EXISTS `FoodDeliveryCompany`.`Customer` (
  `id_customer` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `addr_postal` VARCHAR(222) NOT NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `city` VARCHAR(40) NOT NULL,
  `county` VARCHAR(40) NOT NULL,
  `num_phone` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDeliveryCompany`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDeliveryCompany`.`Store` ;

CREATE TABLE IF NOT EXISTS `FoodDeliveryCompany`.`Store` (
  `id_store` INT NOT NULL AUTO_INCREMENT,
  `addr_postal` VARCHAR(222) NOT NULL,
  `postal_code` VARCHAR(12) NOT NULL,
  `city` VARCHAR(40) NOT NULL,
  `county` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_store`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDeliveryCompany`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDeliveryCompany`.`Employee` ;

CREATE TABLE IF NOT EXISTS `FoodDeliveryCompany`.`Employee` (
  `id_employee` INT NOT NULL AUTO_INCREMENT,
  `id_store` INT NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `nif` VARCHAR(20) NOT NULL,
  `num_phone` VARCHAR(15) NOT NULL,
  `role` ENUM('Cook', 'Delivery') NOT NULL,
  PRIMARY KEY (`id_employee`),
  INDEX `fk_Employee_Store_idx` (`id_store` ASC),
  CONSTRAINT `fk_Employee_Store`
    FOREIGN KEY (`id_store`)
    REFERENCES `FoodDeliveryCompany`.`Store` (`id_store`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDeliveryCompany`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDeliveryCompany`.`Order` ;

CREATE TABLE IF NOT EXISTS `FoodDeliveryCompany`.`Order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_customer` INT NOT NULL,
  `id_store` INT NOT NULL,
  `data_time` DATETIME NOT NULL,
  `delivery_type` ENUM('Home delivery', 'Store pickup') NOT NULL,
  `total_price` FLOAT NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_Order_Customer_idx` (`id_customer` ASC),
  INDEX `fk_Order_Store_idx` (`id_store` ASC),
  CONSTRAINT `fk_Order_Customer`
    FOREIGN KEY (`id_customer`)
    REFERENCES `FoodDeliveryCompany`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Store`
    FOREIGN KEY (`id_store`)
    REFERENCES `FoodDeliveryCompany`.`Store` (`id_store`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDeliveryCompany`.`Delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDeliveryCompany`.`Delivery` ;

CREATE TABLE IF NOT EXISTS `FoodDeliveryCompany`.`Delivery` (
  `id_delivery` INT NOT NULL AUTO_INCREMENT,
  `id_order` INT NOT NULL,
  `id_employee` INT NOT NULL,
  `delivery_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id_delivery`),
  INDEX `fk_Delivery_Employee_idx` (`id_employee` ASC),
  INDEX `fk_Delivery_Order1_idx` (`id_order` ASC),
  CONSTRAINT `fk_Delivery_Employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `FoodDeliveryCompany`.`Employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Delivery_Order1`
    FOREIGN KEY (`id_order`)
    REFERENCES `FoodDeliveryCompany`.`Order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDeliveryCompany`.`PizzaCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDeliveryCompany`.`PizzaCategory` ;

CREATE TABLE IF NOT EXISTS `FoodDeliveryCompany`.`PizzaCategory` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDeliveryCompany`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDeliveryCompany`.`Product` ;

CREATE TABLE IF NOT EXISTS `FoodDeliveryCompany`.`Product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `id_category` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `image` VARCHAR(444) NOT NULL,
  `unit_price` FLOAT NOT NULL,
  `type` ENUM('Pizza', 'Burger', 'Drink') NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `fk_Product_PizzaCategory1_idx` (`id_category` ASC),
  CONSTRAINT `fk_Product_PizzaCategory1`
    FOREIGN KEY (`id_category`)
    REFERENCES `FoodDeliveryCompany`.`PizzaCategory` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodDeliveryCompany`.`OrderProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FoodDeliveryCompany`.`OrderProduct` ;

CREATE TABLE IF NOT EXISTS `FoodDeliveryCompany`.`OrderProduct` (
  `id_order` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_Product_has_Order_Order1_idx` (`id_order` ASC),
  INDEX `fk_Product_has_Order_Product1_idx` (`id_product` ASC),
  PRIMARY KEY (`id_order`, `id_product`),
  CONSTRAINT `fk_Product_has_Order_Product1`
    FOREIGN KEY (`id_product`)
    REFERENCES `FoodDeliveryCompany`.`Product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Order_Order1`
    FOREIGN KEY (`id_order`)
    REFERENCES `FoodDeliveryCompany`.`Order` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
